# Makefile to build the MorphOS SDL2_gfx tests

AR = ppc-morphos-ar
CC	= ppc-morphos-gcc-9
CFLAGS	= -noixemul -O2 -Wall -I/usr/local/include/SDL2
LIBS =  -lSDL2_gfx -lSDL2 -noixemul -lm -lc -L/usr/local/lib
LIBS_TEST = -lSDL2test -L../../SDL-mos-2.0.12-ogl/test
TARGETS = testframerate testgfx testimagefilter testrotozoom	

all: $(TARGETS)

testframerate: testframerate.o
	$(CC) -o $@ $^ $(LIBS_TEST) $(LIBS)

testgfx: testgfx.o
	$(CC) -o $@ $^ $(LIBS_TEST) $(LIBS)

testimagefilter: testimagefilter.o
	$(CC) -o $@ $^ $(LIBS)

testrotozoom: testrotozoom.o
	$(CC) -o $@ $^ $(LIBS_TEST) $(LIBS)

clean:
	rm -f $(TARGETS) *.o $(COBJS) $(TESTLIB)
